# Generated by Django 5.0.3 on 2024-03-22 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("active", "Active"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("personal-accident", "Personal Accident"),
                            ("homeowner-insurance", "Homeowner Insurance"),
                            ("auto", "Auto Insurance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("premium", models.DecimalField(decimal_places=2, max_digits=8)),
                ("cover", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.customer"
                    ),
                ),
            ],
            options={
                "db_table": "quotes",
            },
        ),
    ]
