# Generated by Django 5.0.3 on 2024-03-22 23:21

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_quote"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("personal-accident", "Personal Accident"),
                            ("homeowner-insurance", "Homeowner Insurance"),
                            ("auto", "Auto Insurance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("quoted", "Quoted"),
                            ("new", "New"),
                            ("bound", "Bound"),
                        ],
                        default="quoted",
                        max_length=20,
                    ),
                ),
                ("premium", models.DecimalField(decimal_places=2, max_digits=8)),
                ("cover", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.customer"
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="api.quote"
                    ),
                ),
            ],
            options={
                "db_table": "policies",
            },
        ),
        migrations.CreateModel(
            name="PolicyStateHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("state", models.CharField(max_length=20)),
                (
                    "as_json",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.policy"
                    ),
                ),
            ],
            options={
                "db_table": "policy_state_history",
            },
        ),
    ]
