# Generated by Django 5.0.3 on 2024-03-23 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_policy_policystatehistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policy",
            options={"verbose_name_plural": "policies"},
        ),
        migrations.AlterModelOptions(
            name="policystatehistory",
            options={"verbose_name_plural": "policy state history"},
        ),
    ]
