name: Run tests and lint

on:
  push:
    branches:
      - main
      - dev
      - 'feature/**'
      - 'bugfix/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'poetry'

      - name: Install project dependencies
        run: |
          poetry install --with dev --sync --no-root

      - name: Install and run pre-commit hooks on all files
        run: |
          poetry run pre-commit install --install-hooks
          poetry run pre-commit run --all-files

      - name: Run tests
        run: |
          poetry run coverage run manage.py test api --verbosity=2
          poetry run coverage report
